import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Product } from './product.types';

@Injectable()
export class ProductSeed {
  constructor(
    @InjectModel('Product') private readonly productModel: Model<Product>,
  ) {}

  async seed() {
    const sampleProducts = [
      // Electronics -> Mobiles
      {
        title: 'iPhone 14 Pro',
        description: 'Flagship smartphone with advanced features.',
        rating: 5,
        price: 999,
        quantity: 50,
        brand: 'Apple',
        country: 'USA',
        images: ['iphone14pro.jpg'],
        discount: 10,
        categoryId: '67362dabcd487232b2f86e38',
        subcategoryId: '67362deacd487232b2f86e3b',
        additionalInformation: [{ key: 'Storage', value: '256GB' }],
      },
      {
        title: 'Samsung Galaxy S23',
        description: 'High-performance smartphone with excellent camera.',
        rating: 4,
        price: 850,
        quantity: 40,
        brand: 'Samsung',
        country: 'South Korea',
        images: ['galaxy_s23.jpg'],
        discount: 5,
        categoryId: '67362dabcd487232b2f86e38',
        subcategoryId: '67362deacd487232b2f86e3b',
        additionalInformation: [{ key: 'Storage', value: '128GB' }],
      },
      // Electronics -> Laptops
      {
        title: 'MacBook Air M2',
        description: 'Lightweight and powerful laptop for daily tasks.',
        rating: 5,
        price: 1200,
        quantity: 30,
        brand: 'Apple',
        country: 'USA',
        images: ['macbook_air.jpg'],
        discount: 15,
        categoryId: '67362dabcd487232b2f86e38',
        subcategoryId: '67362e14cd487232b2f86e41',
        additionalInformation: [{ key: 'RAM', value: '16GB' }],
      },
      {
        title: 'Dell XPS 13',
        description: 'Compact laptop with premium build quality.',
        rating: 4,
        price: 1100,
        quantity: 25,
        brand: 'Dell',
        country: 'USA',
        images: ['dell_xps.jpg'],
        discount: 10,
        categoryId: '67362dabcd487232b2f86e38',
        subcategoryId: '67362e14cd487232b2f86e41',
        additionalInformation: [{ key: 'Screen Size', value: '13.4 inches' }],
      },
      // Electronics -> Tablets
      {
        title: 'iPad Pro 11',
        description: 'Tablet for creative professionals.',
        rating: 5,
        price: 900,
        quantity: 20,
        brand: 'Apple',
        country: 'USA',
        images: ['ipad_pro.jpg'],
        discount: 12,
        categoryId: '67362dabcd487232b2f86e38',
        subcategoryId: '67362e25cd487232b2f86e45',
        additionalInformation: [{ key: 'Stylus Support', value: 'Yes' }],
      },
      {
        title: 'Samsung Galaxy Tab S8',
        description: 'Versatile Android tablet with powerful specs.',
        rating: 4,
        price: 750,
        quantity: 30,
        brand: 'Samsung',
        country: 'South Korea',
        images: ['galaxy_tab.jpg'],
        discount: 8,
        categoryId: '67362dabcd487232b2f86e38',
        subcategoryId: '67362e25cd487232b2f86e45',
        additionalInformation: [{ key: 'Battery Life', value: '14 hours' }],
      },
      // Furniture -> Living Room
      {
        title: 'Modern Sofa Set',
        description: 'Comfortable and stylish sofa set for living rooms.',
        rating: 4,
        price: 700,
        quantity: 10,
        brand: 'HomeComfort',
        country: 'Italy',
        images: ['sofa_set.jpg'],
        discount: 20,
        categoryId: '67362e66cd487232b2f86e4a',
        subcategoryId: '67362e8fcd487232b2f86e4d',
        additionalInformation: [{ key: 'Material', value: 'Leather' }],
      },
      {
        title: 'Coffee Table',
        description: 'Elegant wooden coffee table.',
        rating: 3,
        price: 150,
        quantity: 20,
        brand: 'WoodCraft',
        country: 'India',
        images: ['coffee_table.jpg'],
        discount: 10,
        categoryId: '67362e66cd487232b2f86e4a',
        subcategoryId: '67362e8fcd487232b2f86e4d',
        additionalInformation: [{ key: 'Shape', value: 'Round' }],
      },
      // Fashion -> Men's Clothing
      {
        title: "Men's Formal Suit",
        description: 'Elegant suit for business meetings and events.',
        rating: 5,
        price: 250,
        quantity: 15,
        brand: 'StyleMan',
        country: 'UK',
        images: ['mens_suit.jpg'],
        discount: 10,
        categoryId: '67362ee7cd487232b2f86e5a',
        subcategoryId: '67362f07cd487232b2f86e5d',
        additionalInformation: [{ key: 'Material', value: 'Wool Blend' }],
      },
      {
        title: 'Casual T-Shirt',
        description: 'Comfortable and stylish everyday wear.',
        rating: 4,
        price: 20,
        quantity: 50,
        brand: 'CasualLine',
        country: 'USA',
        images: ['casual_tshirt.jpg'],
        discount: 5,
        categoryId: '67362ee7cd487232b2f86e5a',
        subcategoryId: '67362f07cd487232b2f86e5d',
        additionalInformation: [{ key: 'Size', value: 'Medium' }],
      },
      // Fashion -> Women's Clothing
      {
        title: "Women's Evening Dress",
        description: 'Stunning dress for formal occasions.',
        rating: 5,
        price: 300,
        quantity: 10,
        brand: 'ElegantWear',
        country: 'France',
        images: ['evening_dress.jpg'],
        discount: 15,
        categoryId: '67362ee7cd487232b2f86e5a',
        subcategoryId: '67362f1bcd487232b2f86e61',
        additionalInformation: [{ key: 'Color', value: 'Red' }],
      },
      {
        title: 'Casual Blouse',
        description: 'Stylish and comfortable blouse for everyday wear.',
        rating: 4,
        price: 40,
        quantity: 30,
        brand: 'DailyStyle',
        country: 'Italy',
        images: ['casual_blouse.jpg'],
        discount: 5,
        categoryId: '67362ee7cd487232b2f86e5a',
        subcategoryId: '67362f1bcd487232b2f86e61',
        additionalInformation: [{ key: 'Material', value: 'Cotton' }],
      },
    ];

    await this.productModel.insertMany(sampleProducts);
  }
}
